### PR TITLE
I fixed the wget issue.

### PR DESCRIPTION
**Pull request by Quicksticks-oss**
I fixed the wget issue with setup.py by adding wget to the install_requires.

### CODE REVIEW

**Comment by ArEnSc** [comment]
yo sick kk

**Comment by xloem** [comment]
Just a note that I personally use urllib for this functionality which requires no dependency to be installed.

**Comment by ArEnSc** [comment]
> Just a note that I personally use urllib for this functionality which requires no dependency to be installed.

make a pr ill accept it!

**Comment by xloem** [comment]
Here are the lines: https://github.com/xloem/test_matrix_bot/blob/main/module_rwkv.py#L17L19

It again unfortunately looks like the code is untested as there is a case typo preceding it.
```
            if not os.path.exists(fn):
                import urllib.request
                urllib.request.urlretrieve(model_path, fn)
```

**Pull request merged**
