### PR TITLE
allow to set device for pretrained models

### PR DESCRIPTION
**Pull request by xloem**
This is again untested.

I didn't see a way to set the device, so I added two.

It looked like the os.environ assignment logic was backward, so I reversed it to provide for setting a device from the environment.

I also added a forward for `device_type` from `from_pretrained`.

Edited from web. Error-prone.

### CODE REVIEW

**Comment by ArEnSc** [comment]
@xloem ok ill take a look at it sometime next week happy new years! and fix the other things you had commented on

**Comment by ArEnSc** [comment]
@xloem you can call cuda() and cpu() on the model it reinitializes the model with new args

**Comment by ArEnSc** [comment]
let me know if this isn't the case

**Comment by xloem** [comment]
happy new years !

**Comment by xloem** [comment]
because the weights are wrapped in SimpleNamespace you actually have to iterate through the hierarchy manually, and then it looks like it will work [EDIT: oh I see, you made manual wrappers to use rather than the torch ones. i was using the torch ones which fail.]

**Comment by ArEnSc** [comment]
> because the weights are wrapped in SimpleNamespace you actually have to iterate through the hierarchy manually, and then it looks like it will work [EDIT: oh I see, you made manual wrappers to use rather than the torch ones. i was using the torch ones which fail.]

yeah the idea is to get this working even though that isn't as efficient right now

**Comment by ArEnSc** [comment]
So it turns out Fp16 doesn't work properly @xloem I was trying to load a 3B model and it ended up being 12 gb or ram instead of 6gb. This is because it seems like it's missing the application of half to some matricies?

**Comment by xloem** [comment]
You can check the dtype of the tensors to troubleshoot that. Ideally we would find a way to merge work with other implementations.

**Comment by ArEnSc** [comment]
this was addressed

**Pull request closed without merging**
